import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

//material ui
import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';

import { createTheme } from '@mui/material/styles';
import { deepPurple, blue } from '@mui/material/colors';
import { ThemeProvider } from "@emotion/react";


import { Container, TextField } from "@mui/material";
import Popper from '@mui/material/Popper';
import PopupState, { bindToggle, bindPopper } from 'material-ui-popup-state';
import Fade from '@mui/material/Fade';
import Paper from '@mui/material/Paper';

import Start from '@/components/Start';
import { useRef } from 'react'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const theme = createTheme({
    palette: {
      primary: {
        main: '#1565c0',
        secondary: deepPurple,
        ui: blue[900]
      },

    },
  });

  const scrollTargetRef = useRef(null);

  const scrollToTarget = () => {
    scrollTargetRef.current.scrollIntoView({ behavior: 'smooth' })};

 

    return (

      <>
        <div className={`${styles.bg}`}  >
          <ThemeProvider theme={theme}>

            <Container maxWidth="sm" className={`${styles.cot} ${styles.adjust}`}>
              <Typography className={`${styles.para}`} >
                ScamBusters
              </Typography>
              <Button variant="contained" className={`${styles.but}`} onClick={scrollToTarget}>Start</Button>
            </Container>
          </ThemeProvider>
        </div>

        <>
          <Head>
            <title>ScamBuster</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={`${styles.main} ${inter.className}`} ref={scrollTargetRef}>
            

            {/* nav menu */}
            <ThemeProvider theme={theme}>
              <Box sx={{ flexGrow: 1 }} flexDirection="column">
                <AppBar position="static">
                  <Toolbar>
                    <IconButton
                      size="large"
                      edge="start"
                      color="secondary"
                      aria-label="menu"
                      sx={{ mr: 2 }}
                    >
                      {/* <MenuIcon /> */}
                    </IconButton>
                    <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                      ScamBuster
                    </Typography>
                    <Button color="inherit">Login</Button>
                  </Toolbar>
                </AppBar>
              </Box>
            </ThemeProvider>

            {/* form input fields */}
            <Container maxWidth="sm" className={`${styles.cot}`}>
              <div>
                <TextField id="number-input" label="Phone Number" variant="standard" type="number" fullWidth className={`${styles.field}`} size="h1"/>
              </div>
              <div>

                <TextField id="message" label="Message" variant="standard" multiline fullWidth className={`${styles.field}`} f />
              </div>
              <div>


                <PopupState variant="popper" popupId="demo-popup-popper">
                  {(popupState) => (
                    <div>
                      <Button variant="contained" className={`${styles.but}`} size="large" {...bindToggle(popupState)}>Submit</Button>
                      <Popper {...bindPopper(popupState)} transition>
                        {({ TransitionProps }) => (
                          <Fade {...TransitionProps} timeout={350}>
                            <Paper>
                              <Typography sx={{ p: 2 }}>The SMS has been successfully submitted</Typography>
                            </Paper>
                          </Fade>
                        )}
                      </Popper>
                    </div>
                  )}
                </PopupState>

              </div>


            </Container>
          </main>
        </>
      </>





    )
  }

